[package]
name = "ly_events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12.0"
crossbeam = "0.8.1"

ly_input = { path = "../ly_input" }
ly_log = { path = "../ly_log" }
